### ISSUE TITLE
Bug: Not possible to add labels to a secret in unit tests

### ISSUE THREAD

**Issue by gruyaume** [canonical/operator#1098]
# Description

I am trying to create a unit test that will create a secret for the app under test using `add_model_secret`. This method does not accept a `label` parameter and when I try to set a label after the fact, I get this error: 
`You must own secret 'secret:f7249cbc-3480-4742-8b01-2dfcf2148f43' to perform this operation`.

```python
secret_id = self.harness.add_model_secret(
    owner=self.harness.model.app,
    content={"certificate": certificate},
)
secret = self.harness.model.get_secret(id=secret_id)
secret.set_info(label=f"{LIBID}-{csr}")
```

## Version

- Ops 2.9.0

## Logs

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/usr/lib/python3.11/unittest/mock.py", line 1375, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/tls-certificates-interface/tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_requires.py", line 1445, in test_given_certificate_invalid_in_relation_data_when_secret_expired_then_secret_revisions_are_removed
    secret.set_info(label=f"{LIBID}-{csr}")
  File "/home/guillaume/code/tls-certificates-interface/.tox/unit/lib/python3.11/site-packages/ops/model.py", line 1355, in set_info
    self._backend.secret_set(typing.cast(str, self.id),
  File "/home/guillaume/code/tls-certificates-interface/.tox/unit/lib/python3.11/site-packages/ops/testing.py", line 1880, in wrapped
    return orig_method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/tls-certificates-interface/.tox/unit/lib/python3.11/site-packages/ops/testing.py", line 2522, in secret_set
    self._ensure_secret_owner(secret)
  File "/home/guillaume/code/tls-certificates-interface/.tox/unit/lib/python3.11/site-packages/ops/testing.py", line 2489, in _ensure_secret_owner
    raise model.SecretNotFoundError(
ops.model.SecretNotFoundError: You must own secret 'secret:f7249cbc-3480-4742-8b01-2dfcf2148f43' to perform this operation
```

**Comment by gruyaume** [comment]
One workaround is to use `self.harness.model.app.add_secret` but I then loose the ability to run `self.harness.trigger_secret_expiration` because of the same ownership error.

**Comment by tonyandrewmeyer** [comment]
I'm going to assume that this is covered by the above - please do let us know if not! :smile:
