### ISSUE TITLE
Remote app is not added to RelationMapping for relations in some cases

### ISSUE THREAD

**Issue by dshcherb** [canonical/operator#175]
- Two apps, one primary, one subordinate;
- Both have two units;
- A leader subordinate writes app relation data to a container-scoped relation for all primaries to read;
- The first primary observes the leader subordinate (relation-joined) which then writes some data to the app relation data bag;
- The second primary comes up but gets a relation-changed event for the app relation data before it observes (relation-joined) its own subordinate - `relation-list` returns no units.

The reason why it fails is that we currently retrieve a remote app from a remote unit and special-case the peer relation but do not do anything for subordinates we do not yet observe.
https://github.com/canonical/operator/blob/8ef8bd7276a5bacf33d6559db7a381b24a7c8544/ops/model.py#L335-L342

It might be that Juju needs to make a sure subordinate `-joined` event fires first for a primary and only then `-changed` events are fired (created https://bugs.launchpad.net/juju/+bug/1866828).

Additional info:
```
juju status
Model    Controller           Cloud/Region         Version  SLA          Timestamp
default  localhost-localhost  localhost/localhost  2.7.4.1  unsupported  14:09:00+03:00

App           Version  Status   Scale  Charm         Store  Rev  OS      Notes
apache-httpd           error        2  apache-httpd  local    0  ubuntu  
dummy-vhost            waiting    1/2  dummy-vhost   local    0  ubuntu  

Unit              Workload  Agent       Machine  Public address  Ports  Message
apache-httpd/0*   active    idle        0        10.209.240.137         
  dummy-vhost/0*  active    idle                 10.209.240.137         
apache-httpd/1    error     idle        1        10.209.240.253         hook failed: "vhost-config-relation-changed"
  dummy-vhost/1   waiting   allocating           10.209.240.253         agent initializing
```

The unit for which everything is OK:

```
juju show-status-log apache-httpd/0
Time                        Type       Status       Message
10 Mar 2020 14:07:41+03:00  juju-unit  allocating   
10 Mar 2020 14:07:41+03:00  workload   waiting      waiting for machine
10 Mar 2020 14:08:19+03:00  workload   waiting      installing agent
10 Mar 2020 14:08:21+03:00  workload   waiting      agent initializing
10 Mar 2020 14:08:22+03:00  workload   maintenance  installing charm software
10 Mar 2020 14:08:22+03:00  juju-unit  executing    running install hook
10 Mar 2020 14:08:32+03:00  juju-unit  executing    running leader-elected hook
10 Mar 2020 14:08:33+03:00  juju-unit  executing    running config-changed hook
10 Mar 2020 14:08:33+03:00  workload   active       
10 Mar 2020 14:08:33+03:00  juju-unit  executing    running start hook
10 Mar 2020 14:08:34+03:00  juju-unit  idle         
10 Mar 2020 14:08:40+03:00  juju-unit  executing    running vhost-config-relation-joined hook
10 Mar 2020 14:08:41+03:00  juju-unit  executing    running vhost-config-relation-changed hook
10 Mar 2020 14:08:42+03:00  juju-unit  idle         
10 Mar 2020 14:08:57+03:00  juju-unit  executing    running httpd-peer-relation-joined hook
10 Mar 2020 14:08:58+03:00  juju-unit  executing    running httpd-peer-relation-changed hook
10 Mar 2020 14:08:58+03:00  juju-unit  idle         
```

The failing unit:

```juju show-status-log apache-httpd/1
Time                        Type       Status       Message
10 Mar 2020 14:08:44+03:00  workload   waiting      agent initializing
10 Mar 2020 14:08:44+03:00  workload   maintenance  installing charm software
10 Mar 2020 14:08:44+03:00  juju-unit  executing    running install hook
10 Mar 2020 14:08:56+03:00  juju-unit  executing    running leader-settings-changed hook
10 Mar 2020 14:08:56+03:00  juju-unit  executing    running config-changed hook
10 Mar 2020 14:08:56+03:00  workload   active       
10 Mar 2020 14:08:56+03:00  juju-unit  executing    running start hook
10 Mar 2020 14:08:57+03:00  juju-unit  executing    running httpd-peer-relation-joined hook
10 Mar 2020 14:08:58+03:00  juju-unit  executing    running httpd-peer-relation-changed hook
10 Mar 2020 14:08:59+03:00  juju-unit  executing    running vhost-config-relation-changed hook
10 Mar 2020 14:08:59+03:00  juju-unit  error        hook failed: "vhost-config-relation-changed"
```

```
./hooks/vhost-config-relation-changed 
> /var/lib/juju/agents/unit-apache-httpd-1/charm/hooks/vhost-config-relation-changed(212)on_vhost_config_relation_changed()
-> vhosts_serialized = event.relation.data[event.app].get('vhosts')
(Pdb) c
Traceback (most recent call last):
  File "./hooks/vhost-config-relation-changed", line 272, in <module>
    main(Charm)
  File "lib/ops/main.py", line 195, in main
    _emit_charm_event(charm, juju_event_name)
  File "lib/ops/main.py", line 120, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "lib/ops/framework.py", line 199, in emit
    framework._emit(event)
  File "lib/ops/framework.py", line 633, in _emit
    self._reemit(event_path)
  File "lib/ops/framework.py", line 668, in _reemit
    custom_handler(event)
  File "./hooks/vhost-config-relation-changed", line 212, in on_vhost_config_relation_changed
    vhosts_serialized = event.relation.data[event.app].get('vhosts')
  File "lib/ops/model.py", line 372, in __getitem__
    return self._data[key]
KeyError: <ops.model.Application
```

```
(Pdb) dict(event.relation.data)
{<ops.model.Unit apache-httpd/1>: <ops.model.RelationDataContent object at 0x7f5d38f4ab00>, <ops.model.Application apache-httpd>: <ops.model.RelationDataContent object at 0x7f5d38f4aa58>}

```

```
[1]+  Stopped                 ./hooks/vhost-config-relation-changed
root@juju-df5eba-1:/var/lib/juju/agents/unit-apache-httpd-1/charm# relation-ids
vhost-config:1
root@juju-df5eba-1:/var/lib/juju/agents/unit-apache-httpd-1/charm# relation-list
root@juju-df5eba-1:/var/lib/juju/agents/unit-apache-httpd-1/charm# relation-list ; echo $?
0
root@juju-df5eba-1:/var/lib/juju/agents/unit-apache-httpd-1/charm# env | grep JUJU_REMOTE
JUJU_REMOTE_UNIT=
JUJU_REMOTE_APP=dummy-vhost
root@juju-df5eba-1:/var/lib/juju/agents/unit-apache-httpd-1/charm# relation-get --app
vhosts: '- {port: "80", template: PFZpcnR1YWxIb3N0ICo6ODA+CglTZXJ2ZXJBZG1pbiB3ZWJtYXN0ZXJAbG9jYWxob3N0CglEb2N1bWVudFJvb3QgL3Zhci93d3cvZHVtbXktdmhvc3QKCUVycm9yTG9nICR7QVBBQ0hFX0xPR19ESVJ9L2Vycm9yLmxvZwoJQ3VzdG9tTG9nICR7QVBBQ0hFX0xPR19ESVJ9L2FjY2Vzcy5sb2cgY29tYmluZWQKPC9WaXJ0dWFsSG9zdD4K}'
```

```
cat metadata.yaml 
name: apache-httpd
# ... 
requires:
    vhost-config:
        interface: apache-vhost-config
        scope: container
```

**Comment by dshcherb** [comment]
A simple workaround is as follows:

```
    def on_vhost_config_relation_changed(self, event):
        # No subordinate unit observed yet, let's wait until it appears.
        if not event.unit:
            return
        some_value = event.relation.data[event.app].get('some-key')
```

**Comment by dshcherb** [comment]
Turns out it doesn't affect just subordinates but also regular units:

```
juju show-status-log haproxy/1 --days 1
Time                        Type       Status       Message
30 Mar 2020 21:21:15+03:00  juju-unit  allocating   
30 Mar 2020 21:21:15+03:00  workload   waiting      waiting for machine
30 Mar 2020 21:22:03+03:00  workload   waiting      installing agent
30 Mar 2020 21:22:05+03:00  workload   waiting      agent initializing
30 Mar 2020 21:22:06+03:00  workload   maintenance  installing charm software
30 Mar 2020 21:22:07+03:00  juju-unit  executing    running install hook
30 Mar 2020 21:22:14+03:00  juju-unit  executing    running leader-elected hook
30 Mar 2020 21:22:14+03:00  juju-unit  executing    running config-changed hook
30 Mar 2020 21:22:15+03:00  juju-unit  executing    running start hook
30 Mar 2020 21:22:15+03:00  workload   active       
30 Mar 2020 21:22:17+03:00  juju-unit  executing    running proxy-listen-tcp-relation-changed hook
30 Mar 2020 21:22:17+03:00  juju-unit  error        hook failed: "proxy-listen-tcp-relation-changed"

# debug-log
unit-haproxy-1: 21:34:09 DEBUG unit.haproxy/1.proxy-listen-tcp-relation-changed   File "lib/interface_proxy_listen_tcp.py", line 42, in listen_proxies
unit-haproxy-1: 21:34:09 DEBUG unit.haproxy/1.proxy-listen-tcp-relation-changed     app_data = relation.data[relation.app]
unit-haproxy-1: 21:34:09 DEBUG unit.haproxy/1.proxy-listen-tcp-relation-changed   File "lib/ops/model.py", line 422, in __getitem__
unit-haproxy-1: 21:34:09 DEBUG unit.haproxy/1.proxy-listen-tcp-relation-changed     return self._data[key]
unit-haproxy-1: 21:34:09 DEBUG unit.haproxy/1.proxy-listen-tcp-relation-changed KeyError: None
```

**Comment by jameinel** [comment]
So it would be possible for juju to add something like 'relation-list --app'. However, for the event relation-changed, Juju is already setting JUJU_REMOTE_APP rather than relying on relation-list to see the remote units.

**Comment by jameinel** [comment]
I see the problem a bit better. the issue is that the event *does* have a proper app, but that the way the framework builds Relation.data it doesn't know who the app is because it uses relation-list and then assume the app by parsing the units.
