### ISSUE TITLE
Harness: Has errors on charms which define action handlers

### ISSUE THREAD

**Issue by Vultaire** [canonical/operator#231]
Hello,

I'm working on an operator charm which requires a few actions.  The actions appear to be properly defined as I am able to run them via "juju run-action".  However, when attempting to run unit tests, things break.

For a custom action named "custom", set up during the charm's \_\_init\_\_, I run into this traceback for all my Harness-using unit tests:

```
Traceback (most recent call last):
  File "/home/paul-goins/code/charm-foo/tests/unit/test_charm.py", line 122, in test_foo
    self.start_app()
  File "/home/paul-goins/code/charm-foo/tests/unit/test_charm.py", line 42, in start_app
    self.harness.begin()
  File "/home/paul-goins/code/charm-foo/lib/ops/testing.py", line 101, in begin
    self._charm = TestCharm(self._framework, self._framework.meta.name)
  File "/home/paul-goins/code/charm-foo/src/charm.py", line 58, in __init__
    self.framework.observe(self.on.custom_action, self)
AttributeError: 'FooCharmEvents' object has no attribute 'custom_action'
```

**Comment by Vultaire** [comment]
I've traced this being an issue with creating self._meta on the Harness object.  self._create_meta() only works based upon metadata.yaml; it doesn't do anything regarding actions.yaml.  I expect that if actions.yaml could be provided or read automatically in the same way as metadata.yaml, and then provided as the second arg to charm.CharmMeta.from_yaml(), that would resolve the issue.

**Comment by Vultaire** [comment]
I wrote a simple patch which appears to fix the issue.  MR submitted: #232

**Comment by Vultaire** [comment]
In the case anyone hits this prior to a patch being merged, here is a workaround which can be added to a charm's \_\_init\_\_(), prior to attaching handlers for the actions:

```python3
        # Workaround for operator framework issue #231
        # Assumes import: from ops.charm import ActionEvent
        for action_name in (
            "action1",
            "action2",
            "action3",
        ):
            action_name = action_name.replace("-", "_")
            if action_name not in dir(self.on):
                self.on.define_event(action_name + "_action", ActionEvent)
```
