### ISSUE TITLE
StatusBase are registered on instantiation not definition

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#288]
I ran into this if I just run the tests for test_testing.py:
```
$ ./run_tests test/test_testing.py
....................E............
======================================================================
ERROR: test_unit_status (test.test_testing.TestHarness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jameinel/dev/operator/test/test_testing.py", line 679, in test_unit_status
    self.assertEqual(harness.model.unit.status, MaintenanceStatus(''))
  File "/home/jameinel/dev/operator/ops/model.py", line 258, in status
    self._status = StatusBase.from_name(s['status'], s['message'])
  File "/home/jameinel/dev/operator/ops/model.py", line 740, in from_name
    return cls._statuses[name](message)
KeyError: 'maintenance'

----------------------------------------------------------------------
Ran 33 tests in 0.032s
```

This is because the strings aren't registered at import time, but at instance creation time:
```
class StatusBase:
...
    def __new__(cls, *args, **kwargs):
        if cls is StatusBase:
            raise TypeError("cannot instantiate a base class")
        cls._statuses[cls.name] = cls
        return super().__new__(cls)
```

Which means that a 'fix' for the test case is:
```
--- a/test/test_testing.py
+++ b/test/test_testing.py
@@ -676,7 +676,8 @@ class TestHarness(unittest.TestCase):
         harness.set_leader(True)
         harness.begin()
         # default status
-        self.assertEqual(harness.model.unit.status, MaintenanceStatus(''))
+        expected = MaintenanceStatus('')
+        self.assertEqual(harness.model.unit.status, expected)
         status = ActiveStatus('message')
         harness.model.unit.status = status
         self.assertEqual(harness.model.unit.status, status)
```

But I think that isn't the correct fix. The problem is that at *runtime* there is the chance for the status to be anything, and calling self.app.status needs to have the dict populated with possible types for all known strings.

Either we need a metaclass for StatusBase, so that just inheriting from it causes it to be registered, or we add a classmethod that we then call to register after declaring the type.

**Comment by jameinel** [comment]
We agreed that we should just have a dict registry of string name to objects, and just register them in code. It can be a decorator or just a straight function call, but metaclass makes it too "magic" and harder to understand.
