### ISSUE TITLE
use_juju_for_storage=True breaks if collect-metrics is in use

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#347]
On the plus side, you have to actively enable metrics for this to become a problem. Juju does not try to call 'collect-metrics' if there is no 'metrics.yaml' file for a charm.
However, if you do add a metrics.yaml then the charm will fail with:
```
2020-06-30 06:51:09 DEBUG juju.worker.metrics.collect manifold.go:260 recording metrics
2020-06-30 06:51:09 DEBUG juju.worker.uniter.runner runner.go:701 starting jujuc server  {unix @/var/lib/juju/agents/unit-uo-0/metrics-collect-agent.socket <nil>}
2020-06-30 06:51:09 DEBUG worker.uniter.jujuc server.go:209 running hook tool "juju-log"
2020-06-30 06:51:09 DEBUG juju-log Operator Framework 0.7.dev0+unknown up and running.
2020-06-30 06:51:09 DEBUG worker.uniter.jujuc server.go:209 running hook tool "juju-log"
2020-06-30 06:51:09 DEBUG juju-log Legacy hooks/collect-metrics is just a link to ourselves.
2020-06-30 06:51:09 DEBUG worker.uniter.jujuc server.go:209 running hook tool "state-get"
2020-06-30 06:51:09 DEBUG collect-metrics ERROR not implemented for restricted context not implemented
2020-06-30 06:51:09 DEBUG worker.uniter.jujuc server.go:209 running hook tool "juju-log"
2020-06-30 06:51:09 ERROR juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-uo-0/charm/dispatch", line 61, in <module>
    main.main(Ubuntu, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-uo-0/charm/src/ops/main.py", line 302, in main
    framework = ops.framework.Framework(store, charm_dir, meta, model)
  File "/var/lib/juju/agents/unit-uo-0/charm/src/ops/framework.py", line 431, in __init__
    self._stored = self.load_snapshot(stored_handle)
  File "/var/lib/juju/agents/unit-uo-0/charm/src/ops/framework.py", line 520, in load_snapshot
    data = self._storage.load_snapshot(handle.path)
  File "/var/lib/juju/agents/unit-uo-0/charm/src/ops/storage.py", line 183, in load_snapshot
    content = self._backend.get(handle_path)
  File "/var/lib/juju/agents/unit-uo-0/charm/src/ops/storage.py", line 295, in get
    check=True,
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['state-get', 'StoredStateData[_stored]']' returned non-zero exit status 1.
2020-06-30 06:51:09 DEBUG juju.worker.metrics.collect manifold.go:278 ran "collect-metrics" hook (via hook dispatching script: dispatch)
```

Given the current issues wrt collect-metrics, here is my rough proposal:

1) check if state-get is available. If so, continue as any other hook would. That should give us the flexibility if/when Juju starts to treat collect-metrics the same as any other hook.
2) if collect-metrics exists as a script (and not just a symlink to ourselves), invoke it. This will give people a way to *do* metric collection even as an asychronous action, just not within the Operator framework. 
This is mostly because there are lots of other bits of context that are not available during collect-metrics (like relation-get, config-get). If we try to simulate it within the framework, I feel like we're doing them a disservice where they will try to do things that are natural (get_relation, etc), and have it break.
Once (1) is resolved, then they can have full Operator support.
https://discourse.juju.is/t/charm-hooks/1040#heading--collect-metrics

Note that we already don't trigger deferred events during collect-metrics, because we expect them to need context that we know is not available. We can also drop this check as part of (1).

3) Give an appropriate DEBUG message that collect-metrics is being ignored because of lack of support.

**Comment by jameinel** [comment]
Testing shows that (1) isn't sufficient. The command 'state-get' is in PATH, but calling it results in:
```
unit-uo-0: 11:15:03 DEBUG unit.unit-uo-0.collect-metrics ERROR not implemented for restricted context not implemented
```

Trying to trap the content with:
```
EXIT_CODE=0
state-get > stdout 2>stderr || EXIT_CODE=$?
juju-log -l WARNING "return ${EXIT_CODE}; stdout: $(cat stdout); stderr: $(cat stderr)"
```

I get:
```
unit-uo-0: 11:35:28 WARNING unit.unit-uo-0.juju-log return 1; stdout: ; stderr: ERROR not implemented for restricted context not implemented
```

Note that I also filed: https://bugs.launchpad.net/juju/+bug/1885677 since that is a terrible error message.
