### ISSUE TITLE
Error "metric value is too large" when adding floating point metrics with CollectMetricsEvent.add_metrics

### ISSUE THREAD

**Issue by umtdg** [canonical/operator#608]
Hi,

When calling `CollectMetricsEvent.add_metrics` with floating point values, Juju gives [metric value is too large](https://github.com/juju/juju/blob/e13c61a8c69da5ada341012f9d971f6f9e9b78e8/worker/metrics/spool/metrics.go#L226-L228) error. Since this does not happen with integer values, this seems to be caused by decimal conversion resulting in a relatively long floating point number.

Sample charm causing _**metric value is too large**_ error:
```
import logging
import subprocess

from ops.charm import CharmBase
from ops.main import main

logger = logging.getLogger(__name__)


def get_metric(cmd: str) -> float:
    out = subprocess.check_output(cmd, shell=True)
    out = out.decode("utf-8").strip()
    return float(out)


class MetricCharmCharm(CharmBase):
    """Charm the service."""

    def __init__(self, *args):
        super().__init__(*args)

        self.framework.observe(self.on.collect_metrics, self.on_collect_metrics)

    def on_collect_metrics(self, event):
        mem_free = get_metric("free | grep Mem | awk '{print 100*$3/$2}'")
        cpu_util = get_metric("top -b -n2 | grep \"Cpu(s)\"|tail -n 1 | awk '{print $2 + $4}'")

        logger.debug(f"Free memory: {mem_free}")
        logger.debug(f"Cpu utilization: {cpu_util}")

        event.add_metrics({"mem_free": mem_free, "cpu_util": cpu_util})


if __name__ == "__main__":
    main(MetricCharmCharm)
```

_**metrics.yaml**_:
```
metrics:
    cpu_util:
        type: gauge
        description: CPU usage in percentage
    mem_free:
        type: gauge
        description: Free RAM in percentage
```

and error:
```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-metric-charm-1/charm/venv/ops/model.py", line 1284, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-metric-charm-1/add-metric', 'mem_free=2.167170000000000040785153032629750669002532958984375', 'cpu_util=0')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 49, in <module>
    main(MetricCharmCharm)
  File "/var/lib/juju/agents/unit-metric-charm-1/charm/venv/ops/main.py", line 406, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-metric-charm-1/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-metric-charm-1/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-metric-charm-1/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-metric-charm-1/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 45, in on_collect_metrics
    event.add_metrics({"mem_free": mem_free, "cpu_util": cpu_util})
  File "/var/lib/juju/agents/unit-metric-charm-1/charm/venv/ops/charm.py", line 273, in add_metrics
    self.framework.model._backend.add_metrics(metrics, labels)
  File "/var/lib/juju/agents/unit-metric-charm-1/charm/venv/ops/model.py", line 1530, in add_metrics
    self._run(*cmd)
  File "/var/lib/juju/agents/unit-metric-charm-1/charm/venv/ops/model.py", line 1286, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR cannot record metric: metric value is too large\n'

```

**Comment by petevg** [comment]
It looks like the problem here is with the string submitted to the juju agent's metrics command, on the command line, rather than with what the framework does to the float. (I double-checked, and the float, as logged, gets rendered exactly the same by the decimal library. That number is getting passed all the way through to the command line.

I'm still working on a reproducer with the framework eliminated from the picture, so that I can verify the above.

It doesn't (yet) look like we need to change the way that the operator framework handles numbers.

**Comment by petevg** [comment]
Just a note: I did some work to reproduce this last Friday. I wasn't able to do so, and haven't managed to get back to it.

I think the error is getting thrown on the subprocess, by the juju agent. But I'm not sure why the number in question is producing the error.

**Comment by umtdg** [comment]
For me, I was always able to reproduce with these steps:

1. Pack charm using `charmcraft pack`
2. Deploy charm using `juju deploy`
3. Wait for collect-metrics hook to run for the first time (usually right after deployment)
4. Then exception

I deploy charm in these:

- Ubuntu 20.04.3 LTS
- Python 3.8.10
- Juju 2.9.14-ubuntu-amd64
- ops >= 1.2.0
- Charmcraft 1.2.1

with _**metadata.yaml**_:
```
name: metric-charm
series:
  - focal
```

It looks like floating point metric is converted to decimal, then that decimal is converted to string and that string is passed to subprocess using `format()`. I can't see a problem in how the string is passed to Juju, but for using decimal, just to be sure, I did a little experiment:

I generated 100 million random floats in different ranges from (0, 100) to (0, 10 million) (total of 600 million random floats, each 100 million treated separately), using both python's builtin random library and numpy's random library. Passed all the values into `Decimal.from_float`, converted them to string and got the length. Possibility of the length being less than 30 (30 because Juju checks if less than 30, including integer part) was around 1e-05 at best, when floats were in range (0, 10 million).

I also collected my memory usage each second using the same command as the charm. After 2 hours, with approximately 12 thousands entries, applying the same steps as previous, possibility of the length being less than 30 was  4.1e-4

I tested in two different machines, with two different but not so far python versions, both gave similar results:

- Arch Linux with Python 3.9.7
- Ubuntu 20.04.3 LTS with Python 3.8.10

**Comment by jnsgruk** [comment]
Hi @umtdg -- we're still looking at this. As a passing observation, you might consider using [psutil](https://pypi.org/project/psutil/) for gathering system information, rather than shelling out :)

**Comment by erik78se** [comment]
![image](https://user-images.githubusercontent.com/850603/140090181-07e3283a-5af3-465e-ae4c-5284a2cf6a4c.png)

I also get this...

**Comment by petevg** [comment]
@erik78se we haven't cut a release w/ the fix for this just yet. Are you running off of the released version of OF?
