### ISSUE TITLE
Using dashes in storage names crashes unit

### ISSUE THREAD

**Issue by neoaggelos** [canonical/operator#662]
### Summary

I've defined a storage `registry-charm` for my charm with the following snippets in metadata.yaml:

```yaml
....

containers:
  registry:
    ...
    mounts:
      - storage: registry-storage
        location: /var/lib/registry

storage:
  registry-storage:
    type: filesystem
    location: /var/lib/registry
```

This causes my charm to get stuck in `hook failed: "storage-attached"` during installation.

### Logs

```
Traceback (most recent call last):
  File "./src/charm.py", line 76, in <module>
    main(RegistryCharm)
  File "/var/lib/juju/agents/unit-docker-registry-k8s-0/charm/venv/ops/main.py", line 427, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-docker-registry-k8s-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    args, kwargs = _get_event_args(charm, event_to_emit)
  File "/var/lib/juju/agents/unit-docker-registry-k8s-0/charm/venv/ops/main.py", line 163, in _get_event_args
    storages = model.storages[storage_name]
  File "/var/lib/juju/agents/unit-docker-registry-k8s-0/charm/venv/ops/model.py", line 1007, in __getitem__
    storage_list = self._storage_map[storage_name]
KeyError: 'registry'
```

### Investigation

I used `juju debug-hook docker-registry-k8s/0 registry-storage-storage-attached`, waited for hook to restart and then added some extra debugging lines in the charm, which got me this:

```log
root@docker-registry-k8s-0:/var/lib/juju/agents/unit-docker-registry-k8s-0/charm# ./dispatch 
2021-11-03 16:28:54,083 DEBUG    Operator Framework 1.2.0+62.g9baf2ab up and running.
2021-11-03 16:28:54,098 DEBUG    Legacy hooks/registry-storage-storage-attached does not exist.
2021-11-03 16:28:54,109 DEBUG    Using local storage: /var/lib/juju/agents/unit-docker-registry-k8s-0/charm/.unit-state.db already exists
2021-11-03 16:28:54,140 DEBUG    bound_event is: {'emitter': <ops.charm.CharmEvents: collect_metrics, config_changed, ingress_relation_broken, ingress_relation_changed, ingress_relation_created, ingress_relation_departed, ingress_relation_joined, install, leader_elected, leader_settings_changed, post_series_upgrade, pre_series_upgrade, registry_pebble_ready, registry_storage_storage_attached, registry_storage_storage_detaching, remove, start, stop, update_status, upgrade_charm>, 'event_type': <class 'ops.charm.StorageAttachedEvent'>, 'event_kind': 'registry_storage_storage_attached'}, model.storages is: {'_backend': <ops.model._ModelBackend object at 0x7fd490afdfd0>, '_storage_map': {'registry-storage': None}}
2021-11-03 16:28:54,157 DEBUG    self._storage_map is {'registry-storage': None}
2021-11-03 16:28:54,170 ERROR    Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 76, in <module>
    main(RegistryCharm)
  File "/var/lib/juju/agents/unit-docker-registry-k8s-0/charm/venv/ops/main.py", line 427, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-docker-registry-k8s-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    args, kwargs = _get_event_args(charm, event_to_emit)
  File "/var/lib/juju/agents/unit-docker-registry-k8s-0/charm/venv/ops/main.py", line 163, in _get_event_args
    storages = model.storages[storage_name]
  File "/var/lib/juju/agents/unit-docker-registry-k8s-0/charm/venv/ops/model.py", line 1007, in __getitem__
    storage_list = self._storage_map[storage_name]
KeyError: 'registry'
```

From the logs I can see that `event_kind` is `registry_storage_storage_attached` (so the dash has been silently replaced with an underscore). Then, https://github.com/canonical/operator/blob/9baf2ab3deafcaff5d9c6679cdf1d11fc88e3fa3/ops/main.py#L159 goes ahead and drops everything from the underscore onwards (supposedly to drop the `_storage_attached` suffix).

I see that this change was introduced 2 days ago in https://github.com/canonical/operator/commit/9baf2ab3deafcaff5d9c6679cdf1d11fc88e3fa3 from #648.

The charm was successfully working prior to this change.

### Proposed fix

I don't know how straightforward a fix would be in this case without guestimating things about the storage name and the existing storage map. Honestly, I feel like the cleanest solution would be to only allow [A-Za-z0-9] in storage names (and require any existing charms to conform, not aware of any in particular). Glancing over the code I did see a bit of `replace('-', '_')`, so any hacks are only going to cause trouble down the line.

**Comment by jnsgruk** [comment]
Thanks for reporting this, we're looking into it and should have a fix for you soon.
