### ISSUE TITLE
Harness seems to confuse - and _ in storage names

### ISSUE THREAD

**Issue by mmanciop** [canonical/operator#690]
In the metadata.yaml of a charm I am working on there is:

```yaml
storage:
  dynamic-configurations:
    type: filesystem
```

When I run a test using `Harness.begin_with_initial_hooks`, the following error occurs:

```
_______________________________________________________________________ TestTraefikIngressCharm.test_pebble_ready_without_gateway_address ________________________________________________________________________
Traceback (most recent call last):
  File "/home/michele/git/traefik-k8s-operator/tests/unit/test_charm.py", line 31, in test_pebble_ready_without_gateway_address
    self.harness.begin_with_initial_hooks()
  File "/home/michele/git/traefik-k8s-operator/.tox/unit/lib/python3.9/site-packages/ops/testing.py", line 182, in begin_with_initial_hooks
    for storage_index in self._backend.storage_list(storage_name):
  File "/home/michele/git/traefik-k8s-operator/.tox/unit/lib/python3.9/site-packages/ops/testing.py", line 955, in wrapped
    return orig_method(self, *args, **kwargs)
  File "/home/michele/git/traefik-k8s-operator/.tox/unit/lib/python3.9/site-packages/ops/testing.py", line 1132, in storage_list
    return list(index for index in self._storage_list[name]
KeyError: 'dynamic_configurations'
```

Note the swap of `-` for `_`.

If I change the metadata.yaml to use `dynamic_configurations` as the storage name, the error goes away.

**Comment by jameinel** [comment]
It seems likely that we map one way for some things but then fail to map
back. (the attribute and the event would be dynamic_configurations, but the
name would still be dynamic-configurations)

**Comment by rwcarlsen** [comment]
This seems to be what was fixed by https://github.com/canonical/operator/pull/680.  Feel free to reopen with more detail if that hasn't resolved your issues.
