### ISSUE TITLE
[juju secrets] Not able to retrieve a new secret in same execution hook

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/operator#857]
Created a new juju secret and tried to retrieve the secret using id in the same hook execution resulted in SecretNotFoundError.
Expectation is to get newly created secret information.

Sample code to reproduce:
```
    def _test_secrets_action(self, event: ActionEvent) -> None:
        if not self.unit.is_leader():
            event.fail("Please run action on lead unit.")
            return
        logger.warning("test-secrets action event triggered")
        secret = self.model.app.add_secret(
            {'test': 'test'},
            label="test-key",
        )   
        logger.warning(f"Test Secret created: {secret.id}")
        secret_ = self.model.get_secret(id=secret.id)
        data = secret_.get_content()
        logger.warning(f"Test secret retrieved {secret_}")
        event.set_results({"secret": data})
```

Error logs:
```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-keystone-0/charm/./src/charm.py", line 840, in <module>
    main(KeystoneOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/main.py", line 445, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/framework.py", line 914, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-keystone-0/charm/./src/charm.py", line 366, in _on_peer_data_changed
    fernet_secret = self.model.get_secret(id=fernet_secret_id)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 283, in get_secret
    info = self._backend.secret_info_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2873, in secret_info_get
    result = self._run_secret('secret-info-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2837, in _run_secret
    raise SecretNotFoundError() from e
ops.model.SecretNotFoundError
```

Environment details:
```
juju 3.0/edge + microk8s
ops framework -  secrets branch
```

**Comment by wallyworld** [comment]
This may be a juju issue - we will test with the hook commands directly and see if we can reproduce.

**Comment by benhoyt** [comment]
@hemanthnakkina Could you also please paste the full traceback? I suspect there are multiple blocks of traceback given the chained "from e" exception.

**Comment by hemanthnakkina** [comment]
Complete trackback:
```
unit-keystone-0: 08:58:01 WARNING unit.keystone/0.juju-log test-secrets action event triggered
unit-keystone-0: 08:58:01 WARNING unit.keystone/0.juju-log Test Secret created: secret:cdup6gfopaas7rqbqi40
unit-keystone-0: 08:58:01 ERROR unit.keystone/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2499, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-keystone-0/secret-get', 'secret:cdup6gfopaas7rqbqi40', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2834, in _run_secret
    return self._run(*args, return_output=return_output, use_json=use_json)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2505, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR secret "secret:cdup6gfopaas7rqbqi40" not found\n'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 278, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2858, in secret_get
    result = self._run_secret('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2837, in _run_secret
    raise SecretNotFoundError() from e
ops.model.SecretNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2499, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-keystone-0/secret-info-get', 'secret:cdup6gfopaas7rqbqi40', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2834, in _run_secret
    return self._run(*args, return_output=return_output, use_json=use_json)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2505, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR secret "cdup6gfopaas7rqbqi40" not found\n'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-keystone-0/charm/./src/charm.py", line 840, in <module>
    main(KeystoneOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/main.py", line 445, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/framework.py", line 914, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-keystone-0/charm/./src/charm.py", line 306, in _test_secrets_action
    secret_ = self.model.get_secret(id=secret.id)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 283, in get_secret
    info = self._backend.secret_info_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2873, in secret_info_get
    result = self._run_secret('secret-info-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/model.py", line 2837, in _run_secret
    raise SecretNotFoundError() from e
ops.model.SecretNotFoundError
unit-keystone-0: 08:58:01 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
```

**Comment by wallyworld** [comment]
This appears to be a juju bug as I appear to be able to reproduce using the hook commands directly. We can close this issue once we determine for sure by doing a juju fix.

**Comment by ycliuhw** [comment]
This issue should be fixed by https://github.com/juju/juju/pull/14940 now.

**Comment by benhoyt** [comment]
The fix in https://github.com/juju/juju/pull/14940 has been merged now, so closing this.
