### ISSUE TITLE
socket.timeout is not wrapped in a pebble error and shows up in traceback

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#867]
I have [charm code](https://github.com/canonical/cos-configuration-k8s-operator/blob/5bc9ac3721fc4c69dbafd71ce630180b782d8258/src/charm.py#L238) calling pebble.exec inside an APIError guard (should have probably also included ChangeError and ExecError)

```python
        try:
            process = self.container.exec(...)
        except APIError as e:
            # ...
```

But I still got a "bare" `socket.timeout`. Shouldn't we see ChangeError in this case?

https://github.com/canonical/operator/blob/320e7e04e737000abc1d25729ccd29d6e783e6df/ops/pebble.py#L258-L261

```
unit-cos-config-0: 2022-12-08 01:04:57 ERROR unit.cos-config/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 423, in <module>
    main(COSConfigCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 390, in _on_update_status
    self._common_exit_hook()
  File "./src/charm.py", line 174, in _common_exit_hook
    self._exec_sync_repo()
  File "./src/charm.py", line 238, in _exec_sync_repo
    process = self.container.exec(self._git_sync_command_line())
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/model.py", line 1917, in exec
    return self._pebble.exec(
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/pebble.py", line 2280, in exec
    resp = self._request('POST', '/v1/exec', body=body)
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/pebble.py", line 1514, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/pebble.py", line 1552, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/var/lib/juju/agents/unit-cos-config-0/charm/venv/ops/pebble.py", line 260, in http_open
    return self.do_open(_UnixSocketConnection, req,  # type:ignore
  File "/usr/lib/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

**Comment by benhoyt** [comment]
It definitely wouldn't be `ChangeError`, because that has a meaning specific to Pebble changes. There's actually already a `pebble.TimeoutError`, but it's currently only used for a timeout when polling for a change to complete (`wait_change`).

So I actually think just keeping it as `socket.timeout` is appropriate. Incidentally, in [Python 3.10 they made](https://docs.python.org/3/whatsnew/3.10.html#socket) `socket.timeout` just be an alias for the existing, built-in `TimeoutError` exception type. So in my version of Python (3.10) the above shows up as `TimeoutError`.

So if anything we could make this a `pebble.TimeoutError`, but given that's kind of specific to polling for changes, maybe we should leave that as is. I think the code in question above should catch `socket.timeout` (or you could use `TimeoutError` on Python 3.10+).

**Comment by sed-i** [comment]
Catching `socket.timeout` would work but seems too surgical to be documented in the sdk docs.
`TimeoutError` is much nicer but would require charms to use 22.04 (currently all our charms are on 20.04 -- python 3.8).

**Comment by benhoyt** [comment]
Yes, I believe so (though you have to parenthesize multiple exception types). Or if you're stuck on 22.04 you could use `except (pebble.Error, socket.timeout):`.

Going to close this for now. We can always revisit if the above seems to onerous, or we decide we should catch `socket.timeout` in the Pebble code.
