### ISSUE TITLE
Error status causes update-status hook to fail

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/operator#874]
Hi!

I came across a unit in error status for the Prometheus charm:

```
App                 Version  Status   Scale  Charm                     Channel  Rev  Address      Exposed  Message
prometheus          2.33.5   waiting      1  prometheus-k8s            edge      91  10.85.1.74   no       waiting for units settled down

Unit                   Workload  Agent  Address       Ports  Message
prometheus/0*          error     idle   10.86.78.250         hook failed: "update-status"
```

and I've noticed the following error in the charm code:

```
2023-01-03 15:28:08 ERROR juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 774, in <module>
    main(PrometheusCharm)
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/main.py", line 436, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/framework.py", line 866, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 462, in _update_status
    if self.unit.status != ActiveStatus():
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/model.py", line 443, in status
    self._status = StatusBase.from_name(s['status'], s['message'])
  File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/model.py", line 1131, in from_name
    return cls._statuses[name](message)
KeyError: 'error'
```

It seems like the operator is unable to recover from the error because "error" is not an actual status. When the model.py is modified directly in the container the charm is able to recover and reaches an active state.

```
@StatusBase.register
class ErrorStatus(StatusBase):
    name = 'error'

    def __init__(self, message: str = ''):
        super().__init__(message)
```

Unfortunately, I haven't been able to find reproduction steps for the charm to reach that error state without recovering. I hope the information provided will be enough for you to work with.

Possible related to #847 

Thank you!

**Comment by arturo-seijas** [comment]
> Thanks @arturo-seijas! Can you please ensure that #875 fixes this issue?

It does. Thank you
