### ISSUE TITLE
FileNotFoundError: '.../requirements.txt' during `charmcraft pack` with 2.1.0

### ISSUE THREAD

**Issue by Perfect5th** [canonical/operator#913]
Since ops 2.1.0 released, I started getting this error when I `charmcraft pack`:
```
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 :: Running external command ['/root/parts/charm/build/staging-venv/bin/pip3', 'install', '--upgrade', '--no-binary', ':all:', '--requirement=requir
ements.txt']
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    :: Collecting ops>=1.4.0
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::   Using cached ops-2.1.0.tar.gz (228 kB)
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::   Installing build dependencies: started
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::   Installing build dependencies: finished with status 'done'
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::   Getting requirements to build wheel: started
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::   Getting requirements to build wheel: finished with status 'error'
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::   error: subprocess-exited-with-error
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::   × Getting requirements to build wheel did not run successfully.
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::   │ exit code: 1
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::   ╰─> [18 lines of output]
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::       Traceback (most recent call last):
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::         File "/root/parts/charm/build/staging-venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, i
n <module>
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::           main()
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::         File "/root/parts/charm/build/staging-venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, i
n main
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::           json_out['return_val'] = hook(**hook_input['kwargs'])
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::         File "/root/parts/charm/build/staging-venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, i
n get_requires_for_build_wheel
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::           return hook(config_settings)
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::         File "/tmp/pip-build-env-hbo3tdnh/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_bu
ild_wheel
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::           return self._get_build_requires(config_settings, requirements=['wheel'])
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::         File "/tmp/pip-build-env-hbo3tdnh/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::           self.run_setup()
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::         File "/tmp/pip-build-env-hbo3tdnh/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::           super(_BuildMetaLegacyBackend,
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::         File "/tmp/pip-build-env-hbo3tdnh/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::           exec(code, locals())
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::         File "<string>", line 90, in <module>
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::         File "<string>", line 34, in _requirements
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-pmyuzv7y/ops_cc674be2568d44cfb1452b7731e01ff8/requirements
.txt'
2023-02-28 15:57:44.361 :: 2023-02-28 23:57:44.064 ::    ::       [end of output]
```

Was able to get myself unblocked by pinning to 2.0, though.

**Comment by benhoyt** [comment]
Thanks! This is caused by `requirements.txt` not being included in the source distribution by default (via [this commit](https://github.com/canonical/operator/commit/9162c873592499f512b2ea3908cf9578c0fcc4b8#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)).

We could use a [`MANIFEST.in`](https://packaging.python.org/en/latest/guides/using-manifest-in/) rather than relying on the default. However, I think it's probably better to simplify and avoid this, and just duplicate the requirements list statically in `setup.py` (WET vs DRY :-). I'll also add a test to ensure they stay in sync.

I'd also like to add a CI step to build the library and try installing it, to catch issues like this (or even one that does `charmcraft pack`, though that might be trickier).

**Comment by benhoyt** [comment]
2.1.1 released on PyPI that should fix this: https://pypi.org/project/ops/2.1.1/

Thanks again for the quick report. I've fixed the immediate issue fro now, but I'll put a CI step in place to avoid issues like this in future.

**Comment by Perfect5th** [comment]
Awesome, thanks Ben!
