### ISSUE TITLE
Harness filesystem mock for machine charms?

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#917]
For machine charms, is there a way for harness to handle IO calls so test code wouldn't need to mock code around `open` etc?

```
Traceback (most recent call last):
  File "/home/ubuntu/code/grafana-agent-k8s-operator/tests/unit/machine/test_update_status.py", line 31, in setUp
    self.harness.begin_with_initial_hooks()
  File "/home/ubuntu/code/grafana-agent-k8s-operator/.tox/unit/lib/python3.10/site-packages/ops/testing.py", line 348, in begin_with_initial_hooks
    charm.on.config_changed.emit()
  File "/home/ubuntu/code/grafana-agent-k8s-operator/.tox/unit/lib/python3.10/site-packages/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/home/ubuntu/code/grafana-agent-k8s-operator/.tox/unit/lib/python3.10/site-packages/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/home/ubuntu/code/grafana-agent-k8s-operator/.tox/unit/lib/python3.10/site-packages/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/home/ubuntu/code/grafana-agent-k8s-operator/src/grafana_agent.py", line 262, in _update_config
    self.write_file(CONFIG_PATH, yaml.dump(config))
  File "/home/ubuntu/code/grafana-agent-k8s-operator/src/charm.py", line 124, in write_file
    with open(path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/etc/grafana-agent.yaml'
```

**Comment by benhoyt** [comment]
I think this is out of scope for Harness (or any charm testing system for that matter): the charm could do any number of things that aren't ops or Pebble/Juju related, and we can't stop them or try to mock them all. For example, a charm could make an HTTP request, send something to K8s, perform syscalls, and so on. Only the charm will know what it's doing on this front, and how to mock it.

We do do a kind of filesystem emulation in the case of K8s sidecar charms for Pebble push/pull, but that is directly a Pebble/ops concern that we're mocking.

So I'd recommend either explicit mocking (call `self.opener`, which defaults to the builtin `open` but you override in your tests) or patching via `unittest.mock`.
