### ISSUE TITLE
KeyError on secret-expired hook

### ISSUE THREAD

**Issue by ghislainbourgeois** [canonical/operator#943]
When a secret has an expiration time set and the `secret-expired` hook is fired, I get this a ` KeyError: 'JUJU_SECRET_REVISION'`. Here is the full stack trace:

```
unit-tls-certificates-requirer-0: 17:35:12 ERROR unit.tls-certificates-requirer/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 203, in <module>
    main(DummyTLSCertificatesRequirerCharm)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    args, kwargs = _get_event_args(charm, event_to_emit)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/main.py", line 168, in _get_event_args
    args.append(int(os.environ['JUJU_SECRET_REVISION']))
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'JUJU_SECRET_REVISION'
```

The code reproducing this issue is in this [PR](https://github.com/canonical/tls-certificates-interface/pull/43/files#diff-4a6216d13a6e093fbc8e95168864a66e1ad80c3820e95a81fa53c517063d23cdR1351)

I tested with Juju 3.1.2 and 3.2.0, with ops 3.1.2.0.

**Comment by benhoyt** [comment]
We've confirmed this is a bug in Juju, so closing this in favour of https://bugs.launchpad.net/juju/+bug/2023120
