### ISSUE TITLE
Field `working-dir` not found in type plan.Service

### ISSUE THREAD

**Issue by gruyaume** [canonical/operator#988]
## Overview

Using the `working-dir` field in a Pebble service causes `ops.pebble.APIError`.

- ops: 2.5.0
- juju: 3.1.5
- pebble client: v1.2.0+git32.g02ad28a

Here's the pebble layer as defined in the charm:

```python
Layer(
            {
                "summary": "GUI layer",
                "description": "Pebble config layer for the GUI",
                "services": {
                    "gui": {
                        "override": "replace",
                        "startup": "enabled",
                        "command": "node server.js",
                        "working-dir": "/client/standalone/",
                    },
                },
            }
        )
```

Here's the juju debug-log output:

```
unit-sdcore-gui-0: 16:30:01 ERROR unit.sdcore-gui/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/pebble.py", line 1593, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/./src/charm.py", line 221, in <module>
    main(SDCoreGUIOperatorCharm)
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/main.py", line 439, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/framework.py", line 851, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/./src/charm.py", line 87, in _configure_sdcore_gui
    self._configure_pebble(restart=restart)
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/./src/charm.py", line 129, in _configure_pebble
    self._container.add_layer(self._container_name, self._pebble_layer, combine=True)
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/model.py", line 1963, in add_layer
    self._pebble.add_layer(label, layer, combine=combine)
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/pebble.py", line 1877, in add_layer
    self._request('POST', '/v1/layers', body=body)
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/pebble.py", line 1560, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/pebble.py", line 1604, in _request_raw
    raise APIError(body, code, status, message)
ops.pebble.APIError: cannot parse layer YAML: cannot parse layer "gui": yaml: unmarshal errors:
  line 7: field working-dir not found in type plan.Service
unit-sdcore-gui-0: 16:30:01 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-sdcore-gui-0: 16:30:01 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
```

**Comment by benhoyt** [comment]
Unfortunately the Pebble version (daemon version) in Juju 3.1.5 is quite old (this [commit](https://github.com/canonical/pebble/commit/5842ea68c9c7590bb64184b1b7cbff039b02b986)), and `service.working-dir` was added fairly recently (this [commit](https://github.com/canonical/pebble/commit/a807026f3b066efa00e81989900f38c2a151b73f)). I've bumped up Juju's version of Pebble to the latest on the Juju 3.1 branch, so it'll have to wait till Juju 3.1.6 comes out -- hopefully in the next week or two.

If you desperately need a workaround before then, you'll have to do something like set the command to `/bin/sh -c 'cd working-dir; mycommand --foo'`.
